### ISSUE TITLE
[sp18] Lectures/Workshops

### ISSUE THREAD

**Issue by jmuchovej** [ucfsigai/meetings#4]
# `[sp18]` Lectures/Workshops

- [ ] (#5) Search/Space
- [ ] (#6) Intro to Neural Networks (ANNs)
- [ ] (#7) Building an Extensible Neural Network
- [ ] (#8) Deconvoluting Convolutional Neural Networks (CNNs)
- [ ] (#9) Convolving a Neural Network
- [ ] (#10) `<guest>`
- [ ] (#11) Seriously, Neural Networks (RNNs)
- [ ] (#12) Can We Beat Linus [Torvalds]?
- [ ] (#13) Can Machines Learn from Experience? (RL P1)
- [ ] (#14) (RL P2)
- [ ] (#15) Building a Markov Decision Process
